### ISSUE TITLE
gscope3 fails to install its .glade file, without which it cannot start

### ISSUE THREAD

**Issue by HBBroeker** [tefletch/gscope#2]

**Comment by tefletch** [comment]
My original intent was to compile the .glade file into the program but the GTK3 UI is just starting to stabilize, and it has been convenient just to leave the .glade file separate.  For now, just copy the .glade file in the same directory as the gscope binary.   I need to make the installer work correctly both ways.

**Comment by tefletch** [comment]
The UI XML file (gscope3.glade) is now automatically copied to the same location as the program binary by the installer.
