### ISSUE TITLE
Notice of existance

### ISSUE THREAD

**Issue by agvxov** [tefletch/gscope#23]
While i was hunting for the missing file contents of `gscope.c` i found your repo.
I have my own fork of cscope: https://github.com/agvxov/csope.git
It's not quite as reformatted as yours, but I'm working on it. In the soon future I will add ctags support too.

I thought I would let you know, perhaps something will come of it...

**Comment by tefletch** [comment]
Thanks for the notice.  I'll be sure to take a look.  This fork of cscope is also based on version 15.x, but it has:
     - Years of  performance optimizations
     - Massive improvement is scalability (Millions of files with millions of lines an millions of characters)
     - Dozens, if not hundreds of bug fixes
There is a lot more than  just reformatting.  You might find the non-GUI portions of the code useful for comparison.  

Prior to it's public release, gscope  has been utilized by hundreds of users on millions of lines of C and (limited) other languages.
It is extremely stable.

I'm slowly porting gscope to gtk4 right now and will eventually follow up with features/issues listed here.  The GTK team massivly changed their library/framework without a whole lot of regard from mature applications, so will take a while.

**Comment by agvxov** [comment]
*refactoring
my bad. anyways.
